mode: 'og_vae'

model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 128
  loss_type: 'H'
  beta: 1.0

path_params:
  train_path: "/spaths/datasets/vss_pilot_ddp_11f_32x32"
  test_path: "/spaths/datasets/vss_pilot_ddp_test_11f_32x32"

loader_params:
  batch_size: 32
  num_workers: 4

exp_params:
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.9
  kld_weight: 0.0001
  manual_seed: 1265

trainer_params:
  max_epochs: 10

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1265
