model_params:
  name: 'OGVAE'
  in_channels: 3
  latent_dim: 128
  loss_type: 'H'
  beta: 10.0

data_params:
  train_path: "/spaths/datasets/train_ogvae.beton"
  test_path: "/spaths/datasets/test_ogvae.beton"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 10

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1265
