mode: 'scene_vae'

model_params:
  in_channels: 3
  latent_dim: 128

path_params:
  train_path: "/spaths/datasets/ccn_2023_ddp_train_11f_32x32"
  test_path: "/spaths/datasets/ccn_2023_ddp_test_11f_32x32"

loader_params:
  batch_size: 32
  num_workers: 4

exp_params:
  beta: 1.0
  lr: 0.001
  weight_decay: 0.0
  sched_gamma: 0.9
  kld_weight: 0.000001

manual_seed: 1265

trainer_params:
  max_epochs: 10

logging_params:
  save_dir: "/spaths/checkpoints"
  manual_seed: 1265
