---
title: "pilot"
output:
  pdf_document: default
  html_document:
df_print: paged
header-includes:
 \usepackage{booktabs}
 \usepackage{longtable}
 \usepackage{array}
 \usepackage{multirow}
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}

---

# Pilot

```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', 
                      echo=TRUE, warning=FALSE, message=FALSE)
knitr::opts_knit$set(root.dir = '~/env.d/spaths/experiments/')

```



```{r includes}
library(tidyverse)
library(estimatr)
library(ggplot2)
library(readr)

# devtools::install_github("topfunky/gghighcontrast")
library(gghighcontrast)




# th <- theme_classic() +
#   theme(axis.text = element_text(size=26)) +
#   theme(axis.title = element_text(size=30)) 
# theme_set(th)

# update_geom_defaults("point", list(size = 10))
```

```{r load}

exp_name = "1_exit_22x40_doors_rep"

parsed_trials <- read_csv("~/env.d/spaths/experiments/1_exit_22x40_doors_rep/parsed_trials.csv") %>%
    mutate(resp_same = Response == "j",
         correct = !xor(base, resp_same)) %>%
  # trying to remove extra responses at the end
  group_by(ID, TrialOrder) %>%
  filter(row_number() == 1) %>%
  ungroup()

# 8 per row
gaps = c(TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE,
         TRUE, TRUE,  TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, 
         FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE,
         FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE)

gaps <- data.frame(scene = 1:32,
                   gap = gaps)

exp_data <- read_csv("~/output/scenes/1_exit_22x40_doors.csv") %>%
  rename(scene = id) %>%
  left_join(gaps, by = c("scene"))

covariates <- read_csv("~/env.d/spaths/experiments/1_exit_22x40_doors_rep/covariates.csv") %>%
  rename(scene = id) %>%
  mutate(summed_cycles = base_cycles_furniture + move_cycles_furniture,
         summed_cycles_total = base_cycles_total + move_cycles_total,
         summed_cycles_pct = summed_cycles / summed_cycles_total)

exp_data <- exp_data %>%
  left_join(covariates, by = c("scene", "door", "furniture", "move"))

```
```{r}
by_subj <- parsed_trials %>%
  group_by(ID)

hr_by_subj <- by_subj %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n())

fp_by_subj <- by_subj %>%
  filter(base) %>%
  summarise(fp = 1.0 - mean(correct))

subject_performance <- hr_by_subj %>%
  left_join(fp_by_subj, by = "ID") %>%
  mutate(d_hr_fr = hr - fp)

# passed_subjects <- subject_performance
passed_subjects <- subject_performance %>%
  # filter(hr >= 1.75 * fp)
  # filter(hr > 2.0 * fp, n == 64)
  filter(n == 64)

good_data <- passed_subjects %>%
  left_join(parsed_trials)
```
```{r}
good_data %>%
  group_by(ID) %>%
  summarise(n = n())
```

# ```{r} 
# 
# raw_hits <- parsed_trials %>%
#   filter(!base) %>%
#   group_by(scene, door) %>%
#   summarise(c = sum(correct),
#             n = n()) %>%
#   left_join(exp_data)
# 
# raw_hits %>%
#   group_by(d > 0) %>%
#   summarise(c = sum(c))
# 
# raw_hits %>%
#   group_by(flip, d > 0) %>%
#   summarise(c = sum(c),
#             n = n())
# 
# raw_hits %>%
#   group_by(scene, door, d > 0) %>%
#   summarise(c = sum(c)) %>%
#   group_by(scene) %>%
#   summarise(dc = diff(c)) %>%
#   # filter(dc != 0) %>%
#   ggplot(aes(dc)) + 
#   geom_histogram()
# 
# ```


```{r} 

passed_hits <- good_data %>%
  filter(!base) %>%
  group_by(scene, door) %>%
  summarise(c = sum(correct),
            n = n(),
            f = c / n) %>%
  left_join(exp_data)


passed_hits %>%
  group_by(gap, door, d > 0) %>%
  summarise(c = sum(c),
            f = mean(f))


passed_hits %>%
 group_by(scene, d > 0) %>%
 summarise(c = sum(c),
           f = mean(f)) %>%
  group_by(scene) %>%
  summarise(dc = diff(c),
            df = diff(f)) %>%
  ggplot(aes(df)) + 
  geom_histogram(bins = 15)


hr_by_door <- passed_hits %>%
  group_by(scene) %>%
  summarise(f = mean(f)) %>%
  select(scene) %>%
  left_join(passed_hits) %>%
  group_by(door, d > 0) %>%
  summarise(c = sum(c),
            f = mean(f))
 
delta_hr_by_scene <- passed_hits %>%
  arrange(scene, door) %>%
  group_by(scene) %>%
  select(c, f, d, pixeld, starts_with("og"), contains("cycles")) %>%
  summarise(across(everything(), 
                   list(mean = mean, max = max, diff = diff)))
                   # .names = "{.col}_{.fn}"))

  # summarise(dc = diff(c), # difference in raw hits
  #           df = diff(f), # hit rate
  #           maxf = max(f), # maximum hit rate for either condition
  #           muf = mean(f), # average hit rate across conditions
  #           n = sum(n), # number of trials ? 
  #           d = max(d), # maximum difference in idealized 
  #           g = first(g))

delta_hr_by_scene %>%
  ggplot(aes(x = d_diff, y = f_diff)) +
  geom_density2d_filled()



```

```{r}
passed_hits %>%
 ggplot(aes(x = d > 0, y = f)) + 
 geom_boxplot()
```



```{r}
model <- t.test(delta_hr_by_scene$f_diff)
model
```

```{r}

diff_in_path <- passed_hits %>%
  select(scene, door, f) %>%
  pivot_wider(names_from = door, values_from = f,
              names_glue = "door_{door}")
model <- t.test(diff_in_path$door_1,diff_in_path$door_2,  paired = TRUE)
model

diff_in_path %>%
  ungroup() %>%
  summarise(mu_door_1 = mean(door_1),
            mu_door_2 = mean(door_2),
            se_1 = sd(door_1) / sqrt(n()),
            se_2 = sd(door_2) / sqrt(n())
            )
```

```{r}
bar_fig1_df <- data.frame(mu = c(0.29375		,0.40625),
                          std_err = c(0.04707953, 0.02976301),
                          x = factor(c("No Difference", "Difference"))) %>%
  mutate(conf.low = mu - std_err,
         conf.high = mu + std_err)


bar_fig1_df %>%
  ggplot(aes(x = x, y = mu, fill = x)) +
  geom_col() + 
  geom_errorbar(aes(ymin = conf.low, 
                    ymax = conf.high),
                colour = "green",
                size = 2) +
  # xlab("Sensitivity") + 
  # ylab("Diff. in Hit Rate") + 
  # theme_void() + 
  theme_high_contrast(
  foreground_color = "white",
  background_color = "black",
  base_family = "InputMono"
) + 
  theme(axis.text = element_text(size=26),
        axis.title = element_text(size=0))


                          
```


```{r}
model <- good_data %>%
  filter(!base) %>%
  left_join(exp_data, by = c("scene", "door")) %>%
  # with(lm(correct ~ summed_cycles))
  with(lm(correct ~ d > 0))
model %>%
  summary()
```

```{r}
passed_hits %>%
  ungroup() %>%
  select(f, pixeld, contains("cycles"), contains("og")) %>%
  cor

model <- passed_hits %>%
  filter(door == 2) %>%
  with(lm(f ~ summed_cycles)) %>%
  summary()
model
```

```{r}

# th <- theme_minimal() + theme_void() + 
#   theme(axis.text = element_text(size=30)) +
#   theme(axis.title = element_text(size=0))
# theme_set(th)

delta_hr_by_scene %>%
  ggplot(aes(x = summed_cycles_diff, y = f_diff)) +
  geom_point(color = "green", size = 5) + 
  geom_smooth(method = "lm", colour = "purple", size = 2) + 
  xlab("Sensitivity") + 
  ylab("Diff. in Hit Rate") + 
  # theme_void() + 
  theme_high_contrast(
  foreground_color = "white",
  background_color = "black",
  base_family = "InputMono"
) + 
  theme(axis.text = element_text(size=30),
        axis.title = element_text(size=0),
        panel.grid = element_blank()) + 
  coord_fixed(ratio = 0.45)


model <- delta_hr_by_scene %>%
  with(lm(f_diff ~ summed_cycles_diff)) %>%
  summary()
model
```

```{r}
delta_hr_by_scene %>%
  ggplot(aes(x = pixeld_diff, y = f_diff)) +
  geom_point(colour = "red", size = 5) + 
  geom_smooth(method = "lm") + 
  theme_high_contrast(
  foreground_color = "white",
  background_color = "black",
  base_family = "InputMono"
) + 
  theme(axis.text = element_text(size=30),
        axis.title = element_text(size=0),
        panel.grid = element_blank())

model <- delta_hr_by_scene %>%
  with(lm(f_diff ~ pixeld_diff)) %>%
  summary()
model
```


```{r split-half correlation, message=FALSE}
test <- function(x) {
  group_a_names <- good_data %>%
  select(ID) %>%
  distinct %>%
  sample_n(length(ID) / 2)

group_a <- group_a_names %>%
  left_join(good_data, by = 'ID')

group_b <- good_data %>%
  filter(!(ID %in% group_a_names$ID))

a_hr <- group_a %>%
  group_by(scene, door) %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n()) %>%
  ungroup()

b_hr <- group_b %>%
  group_by(scene, door) %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n()) %>%
  ungroup()

a_fp <- group_a %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct)) %>%
  ungroup

b_fp <- group_b %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct)) %>%
  ungroup

a_dprime <- a_hr %>%
  left_join(a_fp, by = "scene") %>%
  # filter(between(hr, 0.0001, 0.999), between(fp, 0.001, 0.999)) %>%
  mutate(ad.prime = qnorm(hr*0.99 + 0.001) - qnorm(fp*0.99 + 0.001)) %>%
  select(scene, door, ad.prime)


ab_dprime <- b_hr %>%
  left_join(b_fp, by = "scene") %>%
  # filter(between(hr, 0.0001, 0.999), between(fp, 0.001, 0.999)) %>%
  mutate(bd.prime = qnorm(hr*0.99 + 0.001) - qnorm(fp*0.99 + 0.001)) %>%
  select(scene, door, bd.prime) %>%
  left_join(a_dprime, by = c("scene", "door"))

# ab_dprime %>%
#   ggplot(aes(x = ad.prime, y = bd.prime)) +
#   geom_point() +
#   geom_smooth(method="lm")

  m <- ab_dprime %>%
    with(lm(bd.prime ~ ad.prime)) %>%
    summary()
  result = m$r.squared
}

split_half <- data.frame(r2 = replicate(1000, test()))

split_half %>%
  ggplot(aes(x = r2)) +
  geom_histogram()

print(mean(split_half$r2))
quantile(split_half$r2, 0.05) %>% print
quantile(split_half$r2, 0.95) %>% print
```






