---
title: "pilot"
output:
  pdf_document: default
  html_document:
df_print: paged
header-includes:
 \usepackage{booktabs}
 \usepackage{longtable}
 \usepackage{array}
 \usepackage{multirow}
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}

---

# Pilot

```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', 
                      echo=TRUE, warning=FALSE, message=FALSE)
knitr::opts_knit$set(root.dir = '~/output/experiments/')

```



```{r includes}
library(tidyverse)
library(estimatr)
library(ggplot2)
library(readr)
library(Hmisc)
library(ggrepel)
library(estimatr)



th <- theme_classic()
theme_set(th)
```

```{r load}

parsed_trials <- read_csv("~/output/experiments/2e_1p_30s_matchedc3/parsed_trials.csv") %>%
    mutate(resp_same = Response == "j",
         correct = !xor(base, resp_same))

exp_data <- read_csv("~/output/scenes/2e_1p_30s_matchedc3.csv") %>%
  rename(scene = id)

covariates <- read_csv("~/output/experiments/2e_1p_30s_matchedc3/covariates.csv")  %>%
  rename(scene = id) %>%
  mutate(zogd = scale(ogd),
         zpixeld = scale(pixeld),
         dsens = move_sense - base_sense)

features <- read_csv("~/output/experiments/2e_1p_30s_matchedc3/features.csv")  %>%
  rename(scene = id)

```

```{r} 

exp_data %>%
  mutate(move_class = move %in% c("up", "down")) %>%
  ggplot(aes(move_class)) +
  geom_bar()

exp_data %>%
  left_join(features) %>%
  left_join(covariates) %>%
  ggplot(aes(x = c3, y = ogd)) +
  geom_point()

exp_data %>%
  left_join(features) %>%
  left_join(covariates) %>%
  ggplot(aes(x = c3_3d, y = ogd)) +
  geom_point()
  
exp_data %>%
  left_join(features) %>%
  left_join(covariates) %>%
  ggplot(aes(x = ogd, y = move_sense)) +
  geom_point()
  

exp_data %>%
  left_join(features) %>%
  left_join(covariates) %>%
  ggplot(aes(x = ogd, y = base_sense)) +
  geom_point()
```


```{r}

by_subj <- parsed_trials %>%
  group_by(ID)

hr_by_subj <- by_subj %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n(),
            wid = first(WID))

fp_by_subj <- by_subj %>%
  filter(base) %>%
  summarise(fp = 1.0 - mean(correct))

subject_performance <- hr_by_subj %>%
  left_join(fp_by_subj, by = "ID")

# passed_subjects <- subject_performance
passed_subjects <- subject_performance %>%
  filter(hr > 1.5*fp, n == 60)

good_data <- passed_subjects %>%
  left_join(parsed_trials)
  

```

```{r}

good_data %>%
  filter(!base) %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  ggplot(aes(x = ogd)) +
  geom_histogram()

good_data %>%
  filter(!base & correct) %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  ggplot(aes(x = ogd)) +
  geom_histogram()


good_data %>%
  filter(!base) %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  group_by(ogd > 0.05) %>%
  count()

good_data %>%
  filter(!base & correct) %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  group_by(ogd > 0.05) %>%
  count()

good_data %>%
  filter(!base) %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  ggplot(aes(x = d)) +
  geom_histogram()


good_data %>%
  filter(!base) %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  ggplot(aes(x = d > 0)) +
  geom_bar()

good_data %>%
  filter(!base & correct) %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  ggplot(aes(x = d > 0)) +
  geom_bar()


```


```{r}

by_trial <- good_data %>%
  group_by(scene, furniture, move)

hr_by_trial <- by_trial %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n()) %>%
  ungroup() %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  left_join(features, by =  c("scene", "furniture", "move"))
  
hr_by_trial %>%
  ggplot(aes(x = d, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of path difference")

  
hr_by_trial %>%
  ggplot(aes(x = lvd, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of path difference")

hr_by_trial %>%
  ggplot(aes(x = ogd, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of oc grid difference")

hr_by_trial %>%
  ggplot(aes(x = pixeld, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of pixel difference")

hr_by_trial %>%
  ggplot(aes(x = c3, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of c3 difference")

hr_by_trial %>%
  ggplot(aes(x = move_sense, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of sensitivity")


hr_by_trial %>%
  with(lm(hr ~ d + pixeld)) %>% 
  summary()

hr_by_trial %>%
  with(lm(hr ~ lvd + pixeld + c5)) %>% 
  summary()

hr_by_trial %>%
  with(lm(hr ~ ogd + pixeld)) %>% 
  summary()

```



```{r dprime}

fp_by_scene <- good_data %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct))

dprime_by_trial <- hr_by_trial %>%
  left_join(fp_by_scene, by = "scene") %>%
  # filter(between(hr, 0.0001, 0.999), between(fp, 0.001, 0.999)) %>%
  # mutate(d.prime = qnorm(hr) - qnorm(fp))
  mutate(d.prime = qnorm(hr*0.99 + 0.001) - qnorm(fp*0.99 + 0.001))


dprime_by_trial %>%
  with(lm(d.prime ~ d + pixeld)) %>%
  summary()

dprime_by_trial %>%
  with(lm(d.prime ~ scale(lvd) + c3)) %>%
  summary()

dprime_by_trial %>%
  with(lm(d.prime ~ scale(ogd) + pixeld)) %>%
  summary()



dprime_by_trial %>%
  ggplot(aes(x = d, y = d.prime, color = pixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")

dprime_by_trial %>%
  ggplot(aes(x = lvd, y = d.prime, color = pixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")


dprime_by_trial %>%
  ggplot(aes(x = ogd, y = d.prime, color = pixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of oc grid difference")

dprime_by_trial %>%
  ggplot(aes(x = ogd, y = fp, color = zpixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("FP as a function of oc grid difference")

dprime_by_trial %>%
  ggplot(aes(x = pixeld, y = d.prime)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of pixel difference")

dprime_by_trial %>%
  ggplot(aes(x = c3, y = d.prime)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of c3 difference")



```

```{r attention}

dprime_by_trial %>%
  ggplot(aes(x = move_sense, y = d.prime)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of sensitivity difference")

dprime_by_trial %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = base_sense, y = d.prime, label = name,
             color = c3_3d)) + 
  geom_point() + 
  geom_text_repel(size=3.5) +
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of sensitivity difference")

dprime_by_trial %>%
  mutate(zc3_3d = scale(c3_3d)) %>%
  # filter(zc3_3d < 0.0) %>%
  filter(c3_3d < 0.97) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = base_sense, y = d.prime, label = name,
             color = c3_3d)) + 
  geom_point() + 
  geom_text_repel(size=3.5) +
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of sensitivity difference")


dprime_by_trial %>%
  with(lm(d.prime ~ base_sense)) %>%
  summary()

dprime_by_trial %>%
  mutate(zc3_3d = scale(c3_3d)) %>%
  # filter(zc3_3d < 0.0) %>%
  filter(c3_3d < 0.97) %>%
  with(lm(d.prime ~ base_sense)) %>%
  summary()

dprime_by_trial %>%
  mutate(zc3_3d = scale(c3_3d)) %>%
  filter(zc3_3d < 0.0) %>%
  # filter(c3_3d < 0.97) %>%
  mutate(name = paste(scene, move),
         move_type = move %in% c("up", "down")) %>%
  ggplot(aes(x = base_sense, y = d.prime, label = name,
             color = zc3_3d)) + 
  geom_point() + 
  geom_text_repel(size=3.5) +
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of sensitivity difference")

# dprime_by_trial %>%
#   with(iv_robust(d.prime ~ scale(base_sense) | c3_3d)) %>%
#   summary()
```
```{r features}

ds_cor <- dprime_by_trial %>%
  select(ogd,pixeld,c1,r1,c2,r2,c3,r3,c4,c5,fc1,fc2,d.prime) %>% 
  as.matrix() %>%
  rcorr(type = "spearman")
print(ds_cor)
```

```{r ogd and c3}

c3_ogd <- dprime_by_trial %>%
  with(lm(ogd ~ c3)) 

c3_dprime <- dprime_by_trial %>%
  with(lm(d.prime ~ c3))

dprime_by_trial$res_ogd = c3_ogd$residuals
dprime_by_trial$res_d.prime = c3_dprime$residuals

dprime_by_trial %>%
  with(lm(res_d.prime ~ res_ogd)) %>%
  summary()

dprime_by_trial %>% 
  ggplot(aes(x = res_ogd, y = res_d.prime)) +
  geom_point() + 
  geom_smooth(method = "lm")


dprime_by_trial %>% 
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = c3, y = d.prime, label =name, color = scale(lvd))) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  geom_smooth(method = "lm")

dprime_by_trial %>% 
  mutate(zc3 = scale(c3)) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = zogd, y = d.prime, label =name, color = zc3)) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  scale_color_gradient(low = "red", high = "blue") +
  geom_smooth(method = "lm")

dprime_by_trial %>% 
  mutate(zc3 = scale(c3)) %>%
  filter(zc3 < 0.0) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = zogd, y = d.prime, label =name, color = zc3)) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  scale_color_gradient(low = "red", high = "blue") +
  geom_smooth(method = "lm")

dprime_by_trial %>% 
  mutate(zc3 = scale(c3)) %>%
  filter(zc3 < 0.0) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = zc3, y = d.prime, label =name, color = zc3)) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  scale_color_gradient(low = "red", high = "blue") +
  geom_smooth(method = "lm")

dprime_by_trial %>% 
  mutate(zc3 = scale(c3)) %>%
  filter(zc3 < 0.0) %>%
  with(lm(d.prime ~ zogd)) %>%
  summary()
```

```{r verifying pytorch3d}

ds_cor <- dprime_by_trial %>%
  select(ogd,pixeld,c3,r3,c3_3d, r3_3d,d.prime) %>% 
  as.matrix() %>%
  rcorr(type = "spearman")
print(ds_cor)

c3_ogd <- dprime_by_trial %>%
  with(lm(ogd ~ c3_3d)) 

c3_dprime <- dprime_by_trial %>%
  with(lm(d.prime ~ c3_3d))

c3_dprime %>%
  summary()


dprime_by_trial %>%
  with(lm(d.prime ~ c3_3d + zogd)) %>%
  summary()

dprime_by_trial$res_ogd = c3_ogd$residuals
dprime_by_trial$res_d.prime = c3_dprime$residuals

dprime_by_trial %>%
  with(lm(res_d.prime ~ res_ogd)) %>%
  summary()

dprime_by_trial %>% 
  ggplot(aes(x = res_ogd, y = res_d.prime)) +
  geom_point() + 
  geom_smooth(method = "lm")


dprime_by_trial %>% 
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = c3_3d, y = d.prime, label =name, color = scale(lvd))) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  geom_smooth(method = "lm")

dprime_by_trial %>% 
  filter(c3_3d < 0.97) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = zogd, y = d.prime, label =name, color = c3_3d)) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  scale_color_gradient(low = "red", high = "blue") +
  geom_smooth(method = "lm")


dprime_by_trial %>% 
  mutate(zc3 = scale(c3_3d)) %>%
  filter(zc3 < 0.0) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = zc3, y = d.prime, label =name, color = zc3)) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  scale_color_gradient(low = "red", high = "blue") +
  geom_smooth(method = "lm")

dprime_by_trial %>% 
  mutate(zc3_3d = scale(c3_3d)) %>%
  with(lm(d.prime ~ zc3_3d)) %>%
  summary()

dprime_by_trial %>% 
  mutate(zc3 = scale(c3)) %>%
  filter(zc3 < 0.0) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = zogd, y = d.prime, label =name, color = zc3)) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  scale_color_gradient(low = "red", high = "blue") +
  geom_smooth(method = "lm")

dprime_by_trial %>% 
  mutate(zc3_3d = scale(c3_3d)) %>%
  filter(zc3_3d < 0) %>%
  mutate(name = paste(scene, move)) %>%
  ggplot(aes(x = zc3_3d, y = d.prime, label =name, color = zogd)) +
  geom_point() + 
  geom_text_repel(size=3.5) +
  scale_color_gradient(low = "red", high = "blue") +
  geom_smooth(method = "lm")


dprime_by_trial %>% 
  mutate(zc3 = scale(c3)) %>%
  filter(c3_3d < 0.97) %>% 
  with(lm(d.prime ~ ogd)) %>%
  summary
```


```{r split-half correlation, message=FALSE}
test <- function() {
  group_a_names <- good_data %>%
  select(ID) %>%
  distinct %>%
  sample_n(length(ID) / 2)

group_a <- group_a_names %>%
  left_join(good_data, by = 'ID')

group_b <- good_data %>%
  filter(!(ID %in% group_a_names$ID))

a_hr <- group_a %>%
  group_by(scene, furniture, move) %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n()) %>%
  ungroup()

b_hr <- group_b %>%
  group_by(scene, furniture, move) %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n()) %>%
  ungroup()

a_fp <- group_a %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct)) %>%
  ungroup

b_fp <- group_b %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct)) %>%
  ungroup

a_dprime <- a_hr %>%
  left_join(a_fp, by = "scene") %>%
  # filter(between(hr, 0.0001, 0.999), between(fp, 0.001, 0.999)) %>%
  mutate(ad.prime = qnorm(hr*0.99 + 0.001) - qnorm(fp*0.99 + 0.001)) %>%
  select(scene, furniture, move, ad.prime)


ab_dprime <- b_hr %>%
  left_join(b_fp, by = "scene") %>%
  # filter(between(hr, 0.0001, 0.999), between(fp, 0.001, 0.999)) %>%
  mutate(bd.prime = qnorm(hr*0.99 + 0.001) - qnorm(fp*0.99 + 0.001)) %>%
  select(scene, furniture, move, bd.prime) %>%
  left_join(a_dprime, by = c("scene", "furniture", "move"))

# ab_dprime %>%
#   ggplot(aes(x = ad.prime, y = bd.prime)) +
#   geom_point() +
#   geom_smooth(method="lm")

  m <- ab_dprime %>%
    with(lm(bd.prime ~ ad.prime)) %>%
    summary()
  result = m$r.squared
}

replicate(100, test()) %>%
  mean %>%
  print()
```

```{r delta dprime}


delta_dprime_by_scene <- dprime_by_trial %>%
  arrange(d) %>%
  group_by(scene) %>%
  summarise(dd.prime = diff(d.prime),
            abs.dd.prime = abs(dd.prime),
            dd = diff(d),
            dlvd = max(lvd),
            dogd = max(ogd),
            dc3 = max(c3),
            dpixeld = diff(pixeld),
            first.d.prime = first(d.prime),
            max.d.prime = max(d.prime),
            prop.dd.prime = dd.prime / abs(first.d.prime)) %>%
  ungroup() %>%
  mutate(zdogd = scale(dogd))


  delta_dprime_by_scene %>%
    ggplot(aes(y = prop.dd.prime, x = dlvd, color = dc3)) +
    geom_jitter() +
    geom_smooth(method = "lm") +
    ggtitle("Change in D' as a function of counterfactual shifts")

delta_dprime_by_scene %>%
ggplot(aes(y = prop.dd.prime, x = dogd, color = dc3)) +
geom_jitter() +
geom_smooth(method = "lm") +
ggtitle("Change in D' as a function of counterfactual shifts")



delta_dprime_by_scene %>%
ggplot(aes(y = prop.dd.prime, x = dc3)) +
geom_jitter() +
geom_smooth(method = "lm") +
ggtitle("Change in D' as a function of counterfactual shifts")



delta_dprime_by_scene %>%
ggplot(aes(x = dd.prime)) +
geom_histogram() +
# geom_histogram(aes(x = dd.prime, color = "raw")) +
ggtitle("Distribution of change in dprime")

delta_dprime_by_scene %>%
with(lm(prop.dd.prime ~ dd + dc3)) %>%
summary()

delta_dprime_by_scene %>%
with(lm(prop.dd.prime ~ dogd + dc3)) %>%
summary()

```
