---
title: "Change detection"
output:
  pdf_document: default
  html_document:
df_print: paged
header-includes:
 \usepackage{booktabs}
 \usepackage{longtable}
 \usepackage{array}
 \usepackage{multirow}
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}

---

# Pilot

```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', 
                      echo=TRUE, warning=FALSE, message=FALSE)
# knitr::opts_knit$set(root.dir = '~/project/spaths/experiments/')

```



```{r includes}

# dependencies and ggplot settings

library(tidyverse)
library(ggplot2)
library(readr)
library(boot)
library(svglite)

library(tidyverse)
```



```{r load}
# Loading data

exp_name = "ccn_2023_exp"
# exp_name = "vss_pilot_inverted"
dataset = "ccn_2023_exp"
exp_path = paste("~/project/spaths/experiments", exp_name,
                 "parsed_trials.csv", sep = "/")
exp_scenes = paste("~/project/spaths/datasets", dataset,
                   "scenes.csv", sep = "/")

parsed_trials <- read_csv(exp_path) %>%
    mutate(resp_same = Response == "j",
           correct = !xor(base, resp_same)) %>%
  # trying to remove extra responses at the end
  group_by(ID, TrialOrder) %>%
  filter(row_number() == 1) %>%
  ungroup()

exp_data <- read_csv(exp_scenes) %>%
  rename(scene = id) 
```


Screening subjects based on overall hit rate (`hr`) and false-positivity rate
(`fp`).
```{r}
by_subj <- parsed_trials %>%
  group_by(ID)

hr_by_subj <- by_subj %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n())

fp_by_subj <- by_subj %>%
  filter(base) %>%
  summarise(fp = 1.0 - mean(correct))

subject_performance <- hr_by_subj %>%
  left_join(fp_by_subj, by = "ID") %>%
  mutate(d_hr_fr = hr - fp)

# passed_subjects <- subject_performance
passed_subjects <- subject_performance %>%
  filter(hr > 0.15) %>%
  filter(d_hr_fr > 0.0) %>%
  # filter(d_hr_fr > 0.07) %>%
  filter(n == 60)

# passed_subjects <- passed_subjects[sample(1:nrow(passed_subjects)),][1:33,]
  

good_data <- passed_subjects %>%
  left_join(parsed_trials, by = "ID")


passed_subjects %>%
  ggplot(aes(d_hr_fr)) + 
  geom_histogram(binwidth = 0.05)
```


Compute the hit rate per trial as well as the difference in hit rate between
scene pairs
```{r} 

passed_hits <- good_data %>%
  filter(!base) %>%
  group_by(scene, door) %>%
  summarise(c = sum(correct), # hit count
            n = n(),          # number of subjects
            f = c / n) %>%    # hit rate
  left_join(exp_data, by = c("scene", "door"))

passed_hits %>%
 group_by(scene, d > 0) %>%
 summarise(c = sum(c),
           f = mean(f)) %>%
  group_by(scene) %>%
  summarise(dc = diff(c),
            df = diff(f)) %>%
  ggplot(aes(df)) + 
  geom_density()


hr_by_door <- passed_hits %>%
  group_by(door, d > 0) %>%
  summarise(c = sum(c),
            f = mean(f))

delta_hr_by_scene <- passed_hits %>%
  arrange(scene, door) %>%
  group_by(scene) %>%
  select(c, f, d, starts_with("og"), contains("cycles")) %>%
  summarise(across(everything(), 
                   list(mean = mean, max = max, min = min, diff = diff))) %>%
  mutate(rel_hr_min = f_min - mean(f_mean),
         rel_hr_max = f_max - mean(f_mean),
         abs_f_diff = abs(f_diff))

delta_hr_by_scene %>%
  summarise(mu = mean(abs_f_diff),
            sd = sd(abs_f_diff),
            n = n(),
            se = sd / sqrt(n))

t0 = mean(delta_hr_by_scene$abs_f_diff)


f1 <- delta_hr_by_scene %>%
  ggplot(aes(abs_f_diff)) +
  geom_vline(xintercept = `t0`, 
             size = 1.25, 
             linetype = "dashed",
             color = "blue") + 
  geom_density(size = 2) + 
  geom_histogram(aes(fill = factor(sign(f_diff)))) +
  theme_classic() + 
  xlab("Absolute Change in Hit Rate") +
  ylab("Frequency") +
  theme(axis.title = element_text(size = 35),
        axis.text = element_text(size = 30),
        legend.position = "none",
        axis.ticks = element_blank())
# summary(path_diff)

# ggsave(file="vss_poster/vss_poster_files/figure-html/abs_chng.svg", plot=f1,
#        width = 9, height = 6)
```

Bootstrap analysis on average absolute difference between pairs.
```{r}

set.seed(0) # TODO: Should we set this seed?
# Returns the absolute pairwise difference (N=30 pairs)
ad_function <- function(data) {
  x <- data %>%
    filter(!base) %>%
    group_by(scene, door) %>%
    summarise(c = sum(!resp_same), # hit count
            hr = c / n(),     # hit rate
              .groups = "keep") %>%
    group_by(scene) %>%
    arrange(door) %>%
    summarise(abs_hr_diff = abs(diff(hr)),
              .groups = "keep")
  return(x$abs_hr_diff) 
}
# Computes the mean absolute pairwise difference
mad_function <- function(data, indices) {
  d <- data.frame(data)
  nr = length(indices)
  d <- d[1:nr,]
  d$resp_same = data$resp_same[indices]
  # d <- data[indices,] #allows boot to permute sample
  # shuffle responses
  # d$resp_same = data$resp_same[0:nr]
  abs_diff <- ad_function(d)
  return(mean(abs_diff)) #return mean absolute difference
}
reps <- boot(data = good_data, 
             statistic=mad_function,
             sim = "permutation",
             parallel = "multicore",
             ncpus = 4,
             R=3000)
#view results of boostrapping
reps
p <- plot(reps)
#calculate adjusted bootstrap percentile (BCa) interval
# boot.ci(reps, type="bca")

sum((reps$t0 < reps$t)) / length(reps$t)

#t0 inv is 0.063
#n = 33
inv_t0 = 0.063

sum((inv_t0 < reps$t)) / length(reps$t)

rdf = data.frame(t = reps$t)
p <- rdf %>%
  ggplot(aes(x = t)) +
  geom_histogram(fill = "grey") +
  geom_vline(xintercept = reps$t0,
             linetype = "dotted",
             size = 3,
             color = "blue") +
   geom_vline(xintercept = inv_t0,
             linetype = "dotted",
             size = 3,
             color = "red") +
  # geom_text(aes(reps$t0, 50),
  #           label = "Observed Change",
  #           vjust = + 30, 
  #           hjust = -0.1) + 
  theme_classic() + 
  xlab("Abs. Change in Hit Rate") +
  ylab("Frequency") +
  theme(axis.title = element_text(size = 25),
        axis.text = element_text(size = 20)) + 
  coord_flip()

# CAREFUL: don't run unless ready to update figure
# ggsave(file="vss_poster/vss_poster_files/figure-html/bs.svg", plot=p,
#        width = 9, height = 7)

```


```{r}

upright_dhr_analysis <- upright_dhr %>%
  rename(upright = f_mean, 
         up_diff = abs_f_diff) %>%
  select(scene, upright, up_diff) %>%
  right_join(delta_hr_by_scene)


f2 <- upright_dhr_analysis %>%
  ggplot(aes(x = f_mean, y = upright)) + 
  geom_point(size = 4.0) + 
  geom_smooth(method = "lm") + 
  theme_classic() + 
  theme(axis.title = element_blank(),
        axis.text = element_text(size = 20),
        ) 

ggsave(file="vss_poster/vss_poster_files/figure-html/results_2_1.svg", plot=f2,
       width = 9, height = 7)

f3 <- upright_dhr_analysis %>%
  ggplot(aes(x = abs_f_diff, y = up_diff)) + 
  geom_point(size = 4.0) + 
  geom_smooth(method = "lm") + 
  theme_classic() + 
  theme(axis.title = element_blank(),
        axis.text = element_text(size = 20))

ggsave(file="vss_poster/vss_poster_files/figure-html/results_2_2.svg", plot=f3,
     width = 9, height = 7)

upright_dhr_analysis %>%
  with(lm(upright ~ f_mean)) %>%
  summary()


upright_dhr_analysis %>%
  with(lm(up_diff ~ abs_f_diff)) %>%
  summary()



t.test(upright_dhr_analysis$up_diff, upright_dhr_analysis$abs_f_diff)

```

### Multi-granular Attention

```{r}
qt_data <- read_csv("~/project/spaths/experiments/ccn_2023_exp/chain_summary_150_25.csv")%>%
  select(scene, tot_diff_geo) %>%
  rename(qt_tot_diff_geo = tot_diff_geo) 
fg_data <- read_csv("~/project/spaths/experiments/ccn_2023_exp_fixed_granularity/chain_summary_150_25.csv")%>%
  select(scene, tot_diff_geo) %>%
  rename(fg_tot_diff_geo = tot_diff_geo)
na_data <- read_csv("~/project/spaths/experiments/ccn_2023_exp_no_attention/chain_summary.csv")%>%
  select(scene, tot_diff_geo) %>%
  rename(na_tot_diff_geo = tot_diff_geo)

all_models <- qt_data %>%
  left_join(fg_data) %>%
  left_join(na_data)

pair_diff <- all_models %>%
  left_join(delta_hr_by_scene)

pair_diff %>%
  ggplot(aes(x = qt_tot_diff_geo, y = f_diff, label = scene)) +
  geom_point() + 
  geom_text(hjust=0, vjust=0)


pair_diff %>%
  ggplot(aes(x = fg_tot_diff_geo, y = f_diff, label = scene)) +
  geom_point() + 
  geom_text(hjust=0, vjust=0)

pair_diff %>%
  ggplot(aes(x = na_tot_diff_geo, y = f_diff, label = scene)) +
  geom_point() + 
  geom_text(hjust=0, vjust=0)

pair_diff %>%
  with(lm(f_diff ~ qt_tot_diff_geo)) %>%
  summary()

pair_diff %>%
  with(lm(f_diff ~ fg_tot_diff_geo)) %>%
  summary()

pair_diff %>%
  with(lm(f_diff ~ na_tot_diff_geo)) %>%
  summary()

```
```{r subject bootstrap}
set.seed(0)

nested_by_subj <- good_data %>%
  nest_by(ID)

metric <- function(data, indices) {
  d = data[indices,] %>% # sample subjects with replacement 
     unnest(cols = c(ID, data))
    
  diff_hr <- d %>%
    filter(!base) %>%
    group_by(scene, door) %>%
    summarise(c = sum(correct), # hit count
              n = n(),          # number of subjects
              f = c / n) %>%    # hit rate
    arrange(scene, door) %>%
    group_by(scene) %>%
    select(c, f) %>%
    summarise(across(everything(), 
                     list(diff = diff)))
  df <- all_models %>% left_join(diff_hr, by = "scene")
  qt_fit <- df %>% with(lm(f_diff ~ qt_tot_diff_geo)) %>% summary
  fg_fit <- df %>% with(lm(f_diff ~ fg_tot_diff_geo)) %>% summary
  na_fit <- df %>% with(lm(f_diff ~ na_tot_diff_geo)) %>% summary

  result <- c(qt_fit$r.squared,
              fg_fit$r.squared,
              na_fit$r.squared,
              qt_fit$r.squared < fg_fit$r.squared,
              qt_fit$r.squared < na_fit$r.squared)
  return(result)
}
reps <- boot(data=nested_by_subj, 
             statistic=metric,
             R=10000, 
             ncpus = 8,
             parallel = "multicore")
#view results of boostrapping
reps
plot(reps)
# CIs
qt_ci <- boot.ci(reps, type="all", index = 1)
qt_mean <- mean(reps$t[,1])
fg_ci <- boot.ci(reps, type="all", index = 2)
fg_mean <- mean(reps$t[,2])
na_ci <- boot.ci(reps, type="all", index = 3)
na_mean <- mean(reps$t[,3])

data.frame(model = c("qt", "fg", "na"),
           mu = c(qt_mean, fg_mean, na_mean),
           c.low = c(qt_ci$percent[4],
                     fg_ci$percent[4],
                     na_ci$percent[4]),
           c.high = c(qt_ci$percent[5],
                     fg_ci$percent[5],
                     na_ci$percent[5])
           
           ) %>%
  ggplot(aes(x = model, y = mu)) +
  geom_col(width = 0.5, position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = c.low, ymax = c.high), width = 0.075, size = 0.7) +
  ylim(0., 0.5) +
  theme(legend.position = "none",
        axis.title = element_blank(),
        # axis.text = element_blank(),
        aspect.ratio = 1
        )


# direct hypothesis testing
fg_vs_qt <- mean(reps$t[, 4])
print(fg_vs_qt)
na_vs_qt <- mean(reps$t[, 5])
print(na_vs_qt)
```
```{r trial bootstrap}
set.seed(0)

metric <- function(data, indices) {
  df = data[indices,] 
  qt_fit <- df %>% with(lm(f_diff ~ qt_tot_diff_geo)) %>% summary
  fg_fit <- df %>% with(lm(f_diff ~ fg_tot_diff_geo)) %>% summary
  na_fit <- df %>% with(lm(f_diff ~ na_tot_diff_geo)) %>% summary

  result <- c(qt_fit$r.squared,
              fg_fit$r.squared,
              na_fit$r.squared,
              qt_fit$r.squared < fg_fit$r.squared,
              qt_fit$r.squared < na_fit$r.squared)
  return(result)
}
reps <- boot(data=pair_diff, 
             statistic=metric,
             R=10000, 
             ncpus = 8,
             parallel = "multicore")
#view results of boostrapping
reps
plot(reps)
# CIs
qt_ci <- boot.ci(reps, type="all", index = 1)
qt_mean <- mean(reps$t[,1])
fg_ci <- boot.ci(reps, type="all", index = 2)
fg_mean <- mean(reps$t[,2])
na_ci <- boot.ci(reps, type="all", index = 3)
na_mean <- mean(reps$t[,3])

boot_df <- data.frame(model = c("quad-tree", "fixed", "no attention"),
           mu = c(qt_mean, fg_mean, na_mean),
           c.low = c(qt_ci$percent[4],
                     fg_ci$percent[4],
                     na_ci$percent[4]),
           c.high = c(qt_ci$percent[5],
                     fg_ci$percent[5],
                     na_ci$percent[5]),
           lesion = factor(c(0, 1, 1)))


th <- theme_classic()
theme_set(th)

boot_df %>%
  ggplot(aes(x = reorder(model, -mu), y = mu, fill=lesion)) +
  geom_col(width = 0.6, position = position_dodge(width = 1.4)) +
  # geom_errorbar(aes(ymin = c.low, ymax = c.high), width = 0.1, size = 0.7) +
  ylim(0., 0.4) +
  theme(legend.position = "none",
        axis.title = element_blank(),
        # axis.text = element_blank(),
        aspect.ratio = 1.5,
        axis.text = element_text(size = 20)
        ) + 
  scale_fill_manual(values = c("#5aa67b", "darkgrey"))


# direct hypothesis testing
fg_vs_qt <- mean(reps$t[, 4])
print(fg_vs_qt)
na_vs_qt <- mean(reps$t[, 5])
print(na_vs_qt)
```

```{r}

hr_by_scene_door <- passed_hits %>%
  group_by(scene, door) %>%
  summarise(across(f, 
                   list(mean = mean)),
            across(-c(f), first))

model <- t.test(f_mean ~ d > 0,
                data = hr_by_scene_door, paired = T)
model
```

```{r}

diff_in_path <- passed_hits %>%
  select(scene, door, f) %>%
  pivot_wider(names_from = door, values_from = f,
              names_glue = "door_{door}")
model <- t.test(diff_in_path$door_1,diff_in_path$door_2,  paired = TRUE)
model

diff_in_path %>%
  ungroup() %>%
  summarise(mu_door_1 = mean(door_1),
            mu_door_2 = mean(door_2),
            se_1 = sd(door_1) / sqrt(n()),
            se_2 = sd(door_2) / sqrt(n())
            )
```

```{r}
bar_fig1_df <- data.frame(mu = c(0.29375		,0.40625),
                          std_err = c(0.04707953, 0.02976301),
                          x = factor(c("No Difference", "Difference"))) %>%
  mutate(conf.low = mu - std_err,
         conf.high = mu + std_err)


bar_fig1_df %>%
  ggplot(aes(x = x, y = mu, fill = x)) +
  geom_col() + 
  geom_errorbar(aes(ymin = conf.low, 
                    ymax = conf.high),
                colour = "green",
                size = 2) +
  # xlab("Sensitivity") + 
  # ylab("Diff. in Hit Rate") + 
  # theme_void() + 
  theme_high_contrast(
  foreground_color = "white",
  background_color = "black",
  base_family = "InputMono"
) + 
  theme(axis.text = element_text(size=26),
        axis.title = element_text(size=0))


                          
```


```{r}
model <- good_data %>%
  filter(!base) %>%
  left_join(exp_data, by = c("scene", "door")) %>%
  # with(lm(correct ~ summed_cycles))
  with(lm(correct ~ d > 0))
model %>%
  summary()
```

```{r}
passed_hits %>%
  ungroup() %>%
  select(f, pixeld, contains("cycles"), contains("og")) %>%
  cor

model <- passed_hits %>%
  filter(door == 2) %>%
  with(lm(f ~ summed_cycles)) %>%
  summary()
model
```

```{r}

# th <- theme_minimal() + theme_void() + 
#   theme(axis.text = element_text(size=30)) +
#   theme(axis.title = element_text(size=0))
# theme_set(th)

delta_hr_by_scene %>%
  ggplot(aes(x = summed_cycles_diff, y = f_diff)) +
  geom_point(color = "green", size = 5) + 
  geom_smooth(method = "lm", colour = "purple", size = 2) + 
  xlab("Sensitivity") + 
  ylab("Diff. in Hit Rate") + 
  # theme_void() + 
  theme_high_contrast(
  foreground_color = "white",
  background_color = "black",
  base_family = "InputMono"
) + 
  theme(axis.text = element_text(size=30),
        axis.title = element_text(size=0),
        panel.grid = element_blank()) + 
  coord_fixed(ratio = 0.45)


model <- delta_hr_by_scene %>%
  with(lm(f_diff ~ summed_cycles_diff)) %>%
  summary()
model
```

```{r}
delta_hr_by_scene %>%
  ggplot(aes(x = pixeld_diff, y = f_diff)) +
  geom_point(colour = "red", size = 5) + 
  geom_smooth(method = "lm") + 
  theme_high_contrast(
  foreground_color = "white",
  background_color = "black",
  base_family = "InputMono"
) + 
  theme(axis.text = element_text(size=30),
        axis.title = element_text(size=0),
        panel.grid = element_blank())

model <- delta_hr_by_scene %>%
  with(lm(f_diff ~ pixeld_diff)) %>%
  summary()
model
```


```{r split-half correlation, message=FALSE}
test <- function(x) {
  group_a_names <- good_data %>%
  select(ID) %>%
  distinct %>%
  sample_n(length(ID) / 2)

group_a <- group_a_names %>%
  left_join(good_data, by = 'ID')

group_b <- good_data %>%
  filter(!(ID %in% group_a_names$ID))

a_hr <- group_a %>%
  group_by(scene, door) %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n()) %>%
  ungroup()

b_hr <- group_b %>%
  group_by(scene, door) %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            n = n()) %>%
  ungroup()

a_fp <- group_a %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct)) %>%
  ungroup

b_fp <- group_b %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct)) %>%
  ungroup

a_dprime <- a_hr %>%
  left_join(a_fp, by = "scene") %>%
  # filter(between(hr, 0.0001, 0.999), between(fp, 0.001, 0.999)) %>%
  mutate(ad.prime = qnorm(hr*0.99 + 0.001) - qnorm(fp*0.99 + 0.001)) %>%
  select(scene, door, ad.prime)


ab_dprime <- b_hr %>%
  left_join(b_fp, by = "scene") %>%
  # filter(between(hr, 0.0001, 0.999), between(fp, 0.001, 0.999)) %>%
  mutate(bd.prime = qnorm(hr*0.99 + 0.001) - qnorm(fp*0.99 + 0.001)) %>%
  select(scene, door, bd.prime) %>%
  left_join(a_dprime, by = c("scene", "door"))

# ab_dprime %>%
#   ggplot(aes(x = ad.prime, y = bd.prime)) +
#   geom_point() +
#   geom_smooth(method="lm")

  m <- ab_dprime %>%
    with(lm(bd.prime ~ ad.prime)) %>%
    summary()
  result = m$r.squared
}

split_half <- data.frame(r2 = replicate(1000, test()))

split_half %>%
  ggplot(aes(x = r2)) +
  geom_histogram()

print(mean(split_half$r2))
quantile(split_half$r2, 0.05) %>% print
quantile(split_half$r2, 0.95) %>% print
```






