---
title: "pilot"
output:
  pdf_document: default
  html_document:
df_print: paged
header-includes:
 \usepackage{booktabs}
 \usepackage{longtable}
 \usepackage{array}
 \usepackage{multirow}
 \usepackage{wrapfig}
 \usepackage{float}
 \floatplacement{figure}{H}

---

# Pilot

```{r global-options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', 
                      echo=TRUE, warning=FALSE, message=FALSE)
knitr::opts_knit$set(root.dir = '~/output/experiments/')

```



```{r includes}
library(tidyverse)
library(estimatr)
library(ggplot2)
library(readr)


th <- theme_classic()
theme_set(th)
```

```{r load}

parsed_trials <- read_csv("~/output/experiments/pilot/parsed_trials.csv")
exp_data <- read_csv("~/output/scenes/pilot.csv") %>%
  rename(scene = id)

covariates <- read_csv("~/output/experiments/pilot/covariates.csv")  %>%
  rename(scene = id)


```

```{r analysis}


ate_data <- parsed_trials %>%
  left_join(exp_data, by = c("scene", "furniture", "move")) %>%
  left_join(covariates, by = c("scene", "furniture", "move")) %>%
  mutate(resp_same = Response == "j",
         correct = !xor(base, resp_same))

```

```{r}

by_subj <- ate_data %>%
  group_by(ID)

hr_by_subj <- by_subj %>%
  filter(!base) %>%
  summarise(hr = mean(correct))

fp_by_subj <- by_subj %>%
  filter(base) %>%
  summarise(fp = 1.0 - mean(correct))

subject_performance <- hr_by_subj %>%
  left_join(fp_by_subj, by = "ID")

passed_subjects <- subject_performance %>%
  filter(hr > 1.5*fp)

good_data <- passed_subjects %>%
  left_join(ate_data)
  

```

```{r}

good_data %>%
  ggplot(aes(x = ogd)) +
  geom_histogram()
good_data %>%
  filter(!base & correct) %>%
  ggplot(aes(x = ogd)) +
  geom_histogram()


good_data %>%
  filter(!base) %>%
  ggplot(aes(x = ogd > 0)) +
  geom_bar()

good_data %>%
  filter(!base & correct) %>%
  ggplot(aes(x = ogd > 0)) +
  geom_bar()

good_data %>%
  filter(!base) %>%
  ggplot(aes(x = d)) +
  geom_histogram()


good_data %>%
  filter(!base) %>%
  ggplot(aes(x = d > 0)) +
  geom_bar()

good_data %>%
  filter(!base & correct) %>%
  ggplot(aes(x = d > 0)) +
  geom_bar()


```


```{r}

by_trial <- good_data %>%
  group_by(scene, furniture, move)

hr_by_trial <- by_trial %>%
  filter(!base) %>%
  summarise(hr = mean(correct),
            d = mean(d),
            pixeld = mean(pixeld),
            lvd = mean(lvd),
            ogd = mean(ogd))

hr_by_trial %>%
  ggplot(aes(x = d, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of path difference")

hr_by_trial %>%
  ggplot(aes(x = ogd, y = hr)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("Hit rate as a function of path difference")

hr_by_trial %>%
  ggplot(aes(x = factor(d), y = hr)) + 
  geom_violin() + 
  ggtitle("Hit rate binned over path difference")


hr_by_trial %>%
  with(lm(hr ~ d + pixeld)) %>% 
  summary()


hr_by_trial %>%
  with(lm(hr ~ ogd + pixeld)) %>% 
  summary()

hr_by_trial %>%
  ggplot(aes(x = factor(d > 0), y = hr)) + 
  geom_violin() + 
  ggtitle("Hit rate binned over path difference")
```

```{r}


delta_hr_by_scene <- hr_by_trial %>%
  arrange(d) %>%
  group_by(scene) %>%
  summarise(dhr = diff(hr),
            dd = diff(d))


delta_hr_by_scene %>%
  with(lm(dhr ~ scale(dd))) %>% 
  summary()

delta_hr_by_scene %>%
  ggplot(aes(dhr)) +
  geom_histogram() +
  ggtitle("Distribution of difference in hr (high - low)")


```

```{r dprime}

fp_by_scene <- good_data %>%
  group_by(scene) %>%
  filter(base) %>%
  summarise(fp = 1 - mean(correct))

dprime_by_trial <- hr_by_trial %>%
  left_join(fp_by_scene, by = "scene") %>%
  mutate(d.prime = qnorm(hr) - qnorm(fp))

dprime_by_trial %>%
  with(lm(d.prime ~ lvd + pixeld)) %>%
  summary()

dprime_by_trial %>%
  with(lm(d.prime ~ scale(ogd) + pixeld)) %>%
  summary()



dprime_by_trial %>%
  ggplot(aes(x = d, y = d.prime, color = pixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")

dprime_by_trial %>%
  ggplot(aes(x = lvd, y = d.prime, color = pixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")

dprime_by_trial %>%
  ggplot(aes(x = ogd, y = d.prime, color = pixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")

dprime_by_trial %>%
  ggplot(aes(x = pixeld, y = d.prime)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")


dprime_by_trial %>%
  ggplot(aes(x = lvd, y = ogd, color = pixeld)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ggtitle("relationship between covariates")

```

```{r delta dprime}


delta_dprime_by_scene <- dprime_by_trial %>%
  arrange(d) %>%
  group_by(scene) %>%
  summarise(dd.prime = diff(d.prime),
            abs.dd.dprime = abs(dd.prime),
            dd = diff(d),
            dogd = diff(ogd),
            dpixeld = diff(pixeld),
            max.d.prime = max(d.prime),
            prop.dd.prime = abs.dd.dprime / max.d.prime) %>%
  ungroup() %>%
  mutate(zdogd = scale(dogd))


delta_dprime_by_scene %>%
  ggplot(aes(y = prop.dd.prime, x = dd, color = max.d.prime)) +
  geom_jitter() +
  geom_smooth(method = "lm") +
  ggtitle("Change in D' as a function of counterfactual shifts")

delta_dprime_by_scene %>%
  ggplot(aes(y = prop.dd.prime, x = dogd, color = max.d.prime)) +
  geom_jitter() +
  geom_smooth(method = "lm") +
  ggtitle("Change in D' as a function of counterfactual shifts")



delta_dprime_by_scene %>%
  ggplot(aes(y = prop.dd.prime, x = dpixeld)) +
  geom_jitter() +
  geom_smooth(method = "lm") +
  ggtitle("Change in D' as a function of counterfactual shifts")



delta_dprime_by_scene %>%
  ggplot(aes(x = prop.dd.prime)) +
  geom_histogram(binwidth = 0.1) +
  ggtitle("Distribution of change in dprime")


```


# ```{r delta dprime cont}
# 
# delta_dprime_by_scene %>%
#   filter(max.d.prime > 1.0) %>%
#   ggplot(aes(y = prop.dd.prime, x = dd)) +
#   geom_point(aes(color = max.d.prime)) +
#   geom_smooth(method = "lm")
# 
# delta_dprime_by_scene %>%
#   filter(max.d.prime > 1.0) %>%
#   ggplot(aes(y = prop.dd.prime, x = dogd)) +
#   geom_point(aes(color = max.d.prime)) +
#   geom_smooth(method = "lm")
# 
# delta_dprime_by_scene %>%
#   with(lm(prop.dd.prime ~ dd + dpixeld)) %>% 
#   summary()
# 
# delta_dprime_by_scene %>%
#   with(lm(prop.dd.prime ~ ogd + dpixeld)) %>% 
#   summary()
# 
# ```
```{r only up/down}

onlyud <- dprime_by_trial %>%
  # group_by(scene) %>%
  filter(move %in% c("up", "down")) %>%
  # filter(!any(move %in% c("left", "right"))) %>%
  select(scene) %>%
  left_join(dprime_by_trial)


onlyud %>%
  ggplot(aes(x = ogd, y = d.prime, color = pixeld)) + 
  geom_jitter() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")


onlyud %>%
  with(lm(d.prime ~ scale(ogd) + pixeld)) %>%
  summary()

```

```{r only left/right}

onlyud <- dprime_by_trial %>%
  # group_by(scene) %>%
  filter(move %in% c("left", "right")) %>%
  # filter(!any(move %in% c("left", "right"))) %>%
  select(scene) %>%
  left_join(dprime_by_trial)


onlyud %>%
  ggplot(aes(x = ogd, y = d.prime, color = pixeld)) + 
  geom_jitter() + 
  geom_smooth(method = "lm") + 
  ggtitle("D-prime as a function of path difference")


onlyud %>%
  with(lm(d.prime ~ scale(ogd) + pixeld)) %>%
  summary()

```